### ISSUE TITLE
[overview] Synthesis workflow improvements

### ISSUE THREAD

**Issue by wytseoortwijn** [TNO/SynthML#298]
Below is an overview of tasks and issues related to the activity synthesis workflow. 

**Simplifications**
- [ ] Don't eliminate 'if' updates in the synthesis chain, since we upgraded to ESCET v9.0, which supports those natively in synthesis. Applies to UML to CIF converter, for synthesis, guard computation, etc.
- [x] #626

**Debugging**
- [ ] #582
- [ ] #458 **(low prio)**

**Consistency and correctness**
- [ ] #543 **(high prio)**
- [x] #539 **(high prio)**
- [ ] For guard computation and the language equivalence check, `UmlToCifTranslator#translateConcreteActivity` places a token on the outgoing control flows of the initial node. However, if these control flows have non-trivial incoming guards, no token may be placed on them. See also https://github.com/TNO/PokaYoke/pull/573#issuecomment-3112661467 and https://github.com/TNO/PokaYoke/pull/573#issuecomment-3108465022. **(high prio)**
- [ ] Run the validator at the very end of the synthesis chain, to ensure that synthesized models are correct.
- [ ] Resolve inconsistencies in maintaining effect indices. See also https://github.com/TNO/PokaYoke/issues/543#issuecomment-3163592911 and https://github.com/TNO/PokaYoke/pull/579#discussion_r2259589723.
- [ ] #556
- [ ] #532
- [ ] #594 
- [x] #643
- [x] #673 

**Vertical scaling**
- [x] #609
- [ ] #685
- [ ] Investigate whether event-based projection can be improved. See also https://github.com/TNO/PokaYoke/issues/410#issuecomment-3083320556.
- [ ] Support synthesis of (abstract) activities that are called by concrete activities. Now you can't have an abstract activity that get's called by a concrete activity. The validator complains about that, saying: "Call behavior actions should call an opaque behavior or a concrete activity." -> Under debate: https://github.com/TNO/PokaYoke/issues/298#issuecomment-3178821927
- [ ] #562
- [x] #553
- [ ] #410
- [ ] #610 
- [x] #618 
- [x] #625
- [ ] #639
- [x] #646 

**Non-atomic actions**
- [ ] Investigate whether the functionality for folding back unfolded (concrete) activities can also be used to fold back unfolded non-atomic actions.
- [ ] In case a non-atomic non-deterministic action couldn't be completely merged by `NonAtomicPatternRewriter`, the different end-events are not merged by `PostProcessActivity#finalizeOpaqueActions`. It makes sense to merge them.
- [ ] Non-atomic patterns could be defined in a slightly more liberal way. Now they are rather specific patterns in the Petri Net structure. For example, the 'end places' in the pattern cannot have other incoming arcs than the ones from the 'end transitions'. But this could be relaxed. Moreover, 'end transitions' can't have fork patterns. However, if the non-atomic action is deterministic, it would be fine to have fork patterns there. We can see this in the ESI Symposium and Bits&Chips models, among others.

**Composite data types**
- [ ] #484 

**Guard computation**
- [ ] #542
- [ ] Discuss the controllability of CIF events generated from post-synthesis models (e.g. a non-merged non-atomic action creates two opaque actions, one for the start event, one for the end event. For guard computation, these are translated as two new start events, both controllable. Similar cases occur with vertical scaling).
- [x] #589

**Scalability**
- [ ] #443
- [x] #648
- [ ] #682 

**Occurrence constraints**
- [ ] #318 **(low prio)**

**Documentation**
- [x] #544 **(high prio)**

**Explainable synthesis**
- [ ] #394 **(low prio)**

**Comment by AndreaPuffo** [comment]
Added #682.

**Comment by wytseoortwijn** [comment]
I've added #685.
