### ISSUE TITLE
Add support for non-atomic actions

### ISSUE THREAD

**Issue by wytseoortwijn** [TNO/SynthML#321]
In the Poka Yoke synthesis workflow (as well as the formal modeling one), actions are assumed to execute atomically. It should be adapted to be able to handle non-atomic actions.

* [x] Adapt profile/stereotype and editing support:
  * [x] Opaque actions
  * [x] Opaque behaviors
  * [x] Call behaviors
* [x] Support in UML to Cameo
* [x] Support in UML to CIF and rest of synthesis chain (#395 and #396).

Follow-ups after having merged #396:
* [x] Generate extra postconditions in the UML-to-CIF translation expressing that no non-atomic action must be active for the postcondition to apply. #398.
* [x] The synthesized activities should be further post-processed. #397.
* [x] Keep the start and end events of non-atomic patterns separated in case they couldn't be merged. #399
* [x] #404.
* [x] The documentation (PDF) needs to be updated. #403.
