### ISSUE TITLE
Support hierarchical UML specifications

### ISSUE THREAD

**Issue by wytseoortwijn** [TNO/SynthML#336]
At the moment, the UML models that we consider should contain a single UML class, which has a list of properties, requirements, actions, and activities. However, it may be desired to be able to specify multiple classes, for example for an number of machine parts, that each have their own set of properties, their own opaque behaviors, and possibly their own activities. This would also improve the modularity of the specifications.

Addresses #265. 

This issue has several sub-tasks. A first list:

* [x] Standardize UML models in terms of allowed types and classes (see #437 and #438).
* [x] Update CifContext to deal with composite data types (see #438).
* [x] Ensure no instantiation cycles are possible in ProfileValidator (see #464).
* [x] Create a flattener class, to flatten the names of properties of type composite data type (see #436).
* [x] Move the flattener to a different plugin (see #456).
* [x] Link the flattening to modeling, verification, simulation, synthesis phases (see #456).
