### ISSUE TITLE
Support vertical scaling: synthesis of activities that call other activities

### ISSUE THREAD

**Issue by wytseoortwijn** [TNO/SynthML#410]
The following steps are needed to implement vertical scaling:
- [x] Allow occurrences/optimality constraints to be expressed over both activities and opaque behaviors. #411.
- [x] Update the documentation according to the change to the occurrences/optimality constraints in the task above. #416.
- [x] Finding all abstract activities in the input UML model and determining the order in which they should be synthesized. #418.
- [x] Allow concrete activities to have preconditions, postconditions (and maybe occurrence constraints). #430.
    - The `PokaYokeProfileValidator` should be adapted to check these constraints.
    - Currently `PNML2UMLTranslator` removes all members of synthesized activities. This should no longer be done.
    - I'm not sure that we also need to keep occurrence constraints. We need to keep pre/postconditions, since they will be used in the UML-to-CIF translation. Occurrence constraints will never be really used I think. Could still be nice for documentation purposes though.
- [x] Revert the changes from #398 for postcondition generation. #431.
    - Right now, no further steps can be taken when the user-written postconditions are satisfied. This has implications for vertical scaling. For example, the final node of a translated concrete activity may no longer be taken. This also means that we'd not be able to fold back an inlined concrete activity. Instead, we should include, as an extra postcondition, that no nonatomic action or atomic nondeterministic action must be active. That is, we should revert our earlier changes.
    - See also #422.
- [x] Implement a translation from concrete UML activities to CIF, in the same style as the UML-to-GAL transformation.
    - See also #3 for initial work on this.
    - This should be an extension of the existing UML-to-CIF transformation, rather than a separate transformation. It should reuse the same atomicity/active variables. It must handle non-atomic and/or non-deterministic actions. Etc. Ideally it would somehow reuse the code of the UML-to-CIF transformation.
    - We should model the call of an activity as a controllable event, and all internal steps of the activity as uncontrollable events. The guard of the controllable event should be the activity precondition, since that's the condition under which the activity can start executing.
    - Occurrence constraints should be expressible over both actions and activities. See also https://github.com/TNO/PokaYoke/pull/418#issuecomment-2498072943.
- [x] Update documentation for updated UML-to-CIF translation. To be done directly after #444.
- [x] Apply activity flattening, so that the UML-to-CIF transformer can translate concrete activities that call other activities. See #548.
- [ ] Apply extra filtering of concrete activities to translate in the UML-to-CIF transformer. So that it doesn't translate all concrete activities, but only the ones that are actually relevant. (Optional / lower prio.)
- [ ] Generate extra postconditions for inlined concrete activities, expressing that there must be no token on any of their control flows. See #562.
- [x] Update event-based projection, to only remove the end events of atomic nondeterministic actions. With the current implementation, they would also remove all uncontrollable events for the inlined concrete activities. See #551.
- [x] Update the Petri Net to UML translator, to translate the nodes of inlined concrete activities. See #553.
  - [ ] Follow-up: #632 
- [x] Handle control flow guards of concrete activities. See #630.
    - [x] Follow-up: #670  
- [ ] Update the choice guard computation, to consider uncontrollable system guards of the actions in inlined concrete activities. See #629 
- [ ] Let non-atomic pattern rewriting handle shadowed `CallBehaviorAction`s.
- [ ] Fold back unfolded/inlined activities. (Right now the synthesis chain inlined concrete activities, without folding them back into call behavior actions.)
- [ ] Update language equivalence check helper to handle flattened nodes correctly.
- [ ] Add tests #679

**Comment by AndreaPuffo** [comment]
Added #670.

**Comment by AndreaPuffo** [comment]
Added #679.

**Comment by AndreaPuffo** [comment]
Linked #701 to language equivalence bullet point.
